# Generated by Django 5.2.16 on 2026-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL used when no featured image is uploaded.', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='image_credit_name',
            field=models.CharField(blank=True, help_text='Optional photographer/creator credit name.', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='image_credit_url',
            field=models.URLField(blank=True, help_text='Optional link to original photo source.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
